/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeDirection = IDL.Variant({
  'LONG' : IDL.Null,
  'SHORT' : IDL.Null,
});
export const ActiveTrade = IDL.Record({
  'direction' : TradeDirection,
  'moduleName' : IDL.Text,
  'tradeId' : IDL.Nat,
  'entryPrice' : IDL.Float64,
  'currentPnl' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TradeResult = IDL.Variant({ 'WIN' : IDL.Null, 'LOSS' : IDL.Null });
export const ClosedTrade = IDL.Record({
  'result' : TradeResult,
  'moduleName' : IDL.Text,
  'tradeId' : IDL.Nat,
  'symbol' : IDL.Text,
  'finalPnl' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addActiveTrade' : IDL.Func(
      [IDL.Text, IDL.Text, TradeDirection, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'closeTrade' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'getActiveTrades' : IDL.Func([], [IDL.Vec(ActiveTrade)], ['query']),
  'getClosedTrades' : IDL.Func([], [IDL.Vec(ClosedTrade)], ['query']),
  'getClosedTradesByModule' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClosedTrade)],
      ['query'],
    ),
  'getClosedTradesByResult' : IDL.Func(
      [TradeResult],
      [IDL.Vec(ClosedTrade)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeDirection = IDL.Variant({ 'LONG' : IDL.Null, 'SHORT' : IDL.Null });
  const ActiveTrade = IDL.Record({
    'direction' : TradeDirection,
    'moduleName' : IDL.Text,
    'tradeId' : IDL.Nat,
    'entryPrice' : IDL.Float64,
    'currentPnl' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TradeResult = IDL.Variant({ 'WIN' : IDL.Null, 'LOSS' : IDL.Null });
  const ClosedTrade = IDL.Record({
    'result' : TradeResult,
    'moduleName' : IDL.Text,
    'tradeId' : IDL.Nat,
    'symbol' : IDL.Text,
    'finalPnl' : IDL.Float64,
  });
  
  return IDL.Service({
    'addActiveTrade' : IDL.Func(
        [IDL.Text, IDL.Text, TradeDirection, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'closeTrade' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'getActiveTrades' : IDL.Func([], [IDL.Vec(ActiveTrade)], ['query']),
    'getClosedTrades' : IDL.Func([], [IDL.Vec(ClosedTrade)], ['query']),
    'getClosedTradesByModule' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClosedTrade)],
        ['query'],
      ),
    'getClosedTradesByResult' : IDL.Func(
        [TradeResult],
        [IDL.Vec(ClosedTrade)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };