/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveTrade {
  'direction' : TradeDirection,
  'moduleName' : string,
  'tradeId' : bigint,
  'entryPrice' : number,
  'currentPnl' : number,
  'symbol' : string,
}
export interface ClosedTrade {
  'result' : TradeResult,
  'moduleName' : string,
  'tradeId' : bigint,
  'symbol' : string,
  'finalPnl' : number,
}
export type TradeDirection = { 'LONG' : null } |
  { 'SHORT' : null };
export type TradeResult = { 'WIN' : null } |
  { 'LOSS' : null };
export interface _SERVICE {
  'addActiveTrade' : ActorMethod<
    [string, string, TradeDirection, number],
    bigint
  >,
  'closeTrade' : ActorMethod<[bigint, number], undefined>,
  'getActiveTrades' : ActorMethod<[], Array<ActiveTrade>>,
  'getClosedTrades' : ActorMethod<[], Array<ClosedTrade>>,
  'getClosedTradesByModule' : ActorMethod<[string], Array<ClosedTrade>>,
  'getClosedTradesByResult' : ActorMethod<[TradeResult], Array<ClosedTrade>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];