/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Zone {
    zoneLabel: string;
    zoneType: ZoneType;
    price: number;
}
export type Time = bigint;
export type PaperTradeState = {
    __kind__: "closed";
    closed: {
        stoppedOut: boolean;
        closedAt: Time;
        tradeNotes: string;
        entryPrice: number;
        exitPrice: number;
        openedAt: Time;
    };
} | {
    __kind__: "open";
    open: {
        behavioralChecklist: string;
        positionManagementNotes: string;
        side: TradeSide;
        setupDescription: string;
        style: TradeStyle;
        target: number;
        contextFilter: string;
        stopLoss: number;
        entryPrice: number;
        riskManagementNotes: string;
        symbol: string;
        openedAt: Time;
    };
};
export interface MarketCacheEntry {
    data: string;
    timestamp: Time;
    symbol: string;
}
export enum TradeSide {
    long_ = "long",
    short_ = "short"
}
export enum TradeStyle {
    scalping = "scalping",
    dayTrade = "dayTrade",
    positionTrade = "positionTrade",
    swingTrade = "swingTrade"
}
export enum ZoneType {
    support = "support",
    resistance = "resistance"
}
export interface backendInterface {
    /**
     * / Add a new support/resistance zone
     */
    addZone(price: number, zoneLabel: string, zoneType: ZoneType): Promise<bigint>;
    /**
     * / Close a paper trade
     */
    closePaperTrade(id: bigint, exitPrice: number, stoppedOut: boolean, tradeNotes: string): Promise<boolean>;
    /**
     * / Delete a zone by id
     */
    deleteZone(id: bigint): Promise<boolean>;
    /**
     * / Get all market cache data
     */
    getAllMarketCache(): Promise<Array<MarketCacheEntry>>;
    /**
     * / Get all paper trades
     */
    getAllTrades(): Promise<Array<PaperTradeState>>;
    /**
     * / Get all closed trades
     */
    getClosedTrades(): Promise<Array<{
        trade: PaperTradeState;
        tradeId: bigint;
    }>>;
    /**
     * / Get market cache data by id
     */
    getMarketCache(id: bigint): Promise<MarketCacheEntry | null>;
    /**
     * / Get all market cache data for a symbol
     */
    getMarketCacheForSymbol(symbol: string): Promise<Array<MarketCacheEntry>>;
    /**
     * / Get all open trades
     */
    getOpenTrades(): Promise<Array<{
        trade: PaperTradeState;
        tradeId: bigint;
    }>>;
    /**
     * / Get trade by id
     */
    getTrade(id: bigint): Promise<PaperTradeState | null>;
    /**
     * / Get trades for a symbol
     */
    getTradesForSymbol(symbol: string): Promise<Array<PaperTradeState>>;
    /**
     * / Get all zones
     */
    getZones(): Promise<Array<Zone>>;
    /**
     * / Open a new paper trade
     */
    openPaperTrade(symbol: string, side: TradeSide, entryPrice: number, stopLoss: number, target: number, style: TradeStyle, setupDescription: string, contextFilter: string, riskManagementNotes: string, positionManagementNotes: string, behavioralChecklist: string): Promise<bigint>;
    /**
     * / Store market data cache entry
     */
    storeMarketCache(symbol: string, data: string): Promise<bigint>;
}
import type { MarketCacheEntry as _MarketCacheEntry, PaperTradeState as _PaperTradeState, Time as _Time, TradeSide as _TradeSide, TradeStyle as _TradeStyle, Zone as _Zone, ZoneType as _ZoneType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addZone(arg0: number, arg1: string, arg2: ZoneType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addZone(arg0, arg1, to_candid_ZoneType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addZone(arg0, arg1, to_candid_ZoneType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async closePaperTrade(arg0: bigint, arg1: number, arg2: boolean, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.closePaperTrade(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closePaperTrade(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteZone(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteZone(arg0);
            return result;
        }
    }
    async getAllMarketCache(): Promise<Array<MarketCacheEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketCache();
            return result;
        }
    }
    async getAllTrades(): Promise<Array<PaperTradeState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClosedTrades(): Promise<Array<{
        trade: PaperTradeState;
        tradeId: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedTrades();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedTrades();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketCache(arg0: bigint): Promise<MarketCacheEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketCache(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketCache(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketCacheForSymbol(arg0: string): Promise<Array<MarketCacheEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketCacheForSymbol(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketCacheForSymbol(arg0);
            return result;
        }
    }
    async getOpenTrades(): Promise<Array<{
        trade: PaperTradeState;
        tradeId: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenTrades();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenTrades();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: bigint): Promise<PaperTradeState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesForSymbol(arg0: string): Promise<Array<PaperTradeState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesForSymbol(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesForSymbol(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZones(): Promise<Array<Zone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZones();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZones();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async openPaperTrade(arg0: string, arg1: TradeSide, arg2: number, arg3: number, arg4: number, arg5: TradeStyle, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.openPaperTrade(arg0, to_candid_TradeSide_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_TradeStyle_n22(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openPaperTrade(arg0, to_candid_TradeSide_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_TradeStyle_n22(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async storeMarketCache(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMarketCache(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMarketCache(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PaperTradeState_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaperTradeState): PaperTradeState {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSide_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSide): TradeSide {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TradeStyle_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeStyle): TradeStyle {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ZoneType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ZoneType): ZoneType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Zone_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Zone): Zone {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketCacheEntry]): MarketCacheEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaperTradeState]): PaperTradeState | null {
    return value.length === 0 ? null : from_candid_PaperTradeState_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trade: _PaperTradeState;
    tradeId: bigint;
}): {
    trade: PaperTradeState;
    tradeId: bigint;
} {
    return {
        trade: from_candid_PaperTradeState_n4(_uploadFile, _downloadFile, value.trade),
        tradeId: value.tradeId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zoneLabel: string;
    zoneType: _ZoneType;
    price: number;
}): {
    zoneLabel: string;
    zoneType: ZoneType;
    price: number;
} {
    return {
        zoneLabel: value.zoneLabel,
        zoneType: from_candid_ZoneType_n18(_uploadFile, _downloadFile, value.zoneType),
        price: value.price
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    behavioralChecklist: string;
    positionManagementNotes: string;
    side: _TradeSide;
    setupDescription: string;
    style: _TradeStyle;
    target: number;
    contextFilter: string;
    stopLoss: number;
    entryPrice: number;
    riskManagementNotes: string;
    symbol: string;
    openedAt: _Time;
}): {
    behavioralChecklist: string;
    positionManagementNotes: string;
    side: TradeSide;
    setupDescription: string;
    style: TradeStyle;
    target: number;
    contextFilter: string;
    stopLoss: number;
    entryPrice: number;
    riskManagementNotes: string;
    symbol: string;
    openedAt: Time;
} {
    return {
        behavioralChecklist: value.behavioralChecklist,
        positionManagementNotes: value.positionManagementNotes,
        side: from_candid_TradeSide_n7(_uploadFile, _downloadFile, value.side),
        setupDescription: value.setupDescription,
        style: from_candid_TradeStyle_n9(_uploadFile, _downloadFile, value.style),
        target: value.target,
        contextFilter: value.contextFilter,
        stopLoss: value.stopLoss,
        entryPrice: value.entryPrice,
        riskManagementNotes: value.riskManagementNotes,
        symbol: value.symbol,
        openedAt: value.openedAt
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scalping: null;
} | {
    dayTrade: null;
} | {
    positionTrade: null;
} | {
    swingTrade: null;
}): TradeStyle {
    return "scalping" in value ? TradeStyle.scalping : "dayTrade" in value ? TradeStyle.dayTrade : "positionTrade" in value ? TradeStyle.positionTrade : "swingTrade" in value ? TradeStyle.swingTrade : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    support: null;
} | {
    resistance: null;
}): ZoneType {
    return "support" in value ? ZoneType.support : "resistance" in value ? ZoneType.resistance : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: {
        stoppedOut: boolean;
        closedAt: _Time;
        tradeNotes: string;
        entryPrice: number;
        exitPrice: number;
        openedAt: _Time;
    };
} | {
    open: {
        behavioralChecklist: string;
        positionManagementNotes: string;
        side: _TradeSide;
        setupDescription: string;
        style: _TradeStyle;
        target: number;
        contextFilter: string;
        stopLoss: number;
        entryPrice: number;
        riskManagementNotes: string;
        symbol: string;
        openedAt: _Time;
    };
}): {
    __kind__: "closed";
    closed: {
        stoppedOut: boolean;
        closedAt: Time;
        tradeNotes: string;
        entryPrice: number;
        exitPrice: number;
        openedAt: Time;
    };
} | {
    __kind__: "open";
    open: {
        behavioralChecklist: string;
        positionManagementNotes: string;
        side: TradeSide;
        setupDescription: string;
        style: TradeStyle;
        target: number;
        contextFilter: string;
        stopLoss: number;
        entryPrice: number;
        riskManagementNotes: string;
        symbol: string;
        openedAt: Time;
    };
} {
    return "closed" in value ? {
        __kind__: "closed",
        closed: value.closed
    } : "open" in value ? {
        __kind__: "open",
        open: from_candid_record_n6(_uploadFile, _downloadFile, value.open)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): TradeSide {
    return "long" in value ? TradeSide.long : "short" in value ? TradeSide.short : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    trade: _PaperTradeState;
    tradeId: bigint;
}>): Array<{
    trade: PaperTradeState;
    tradeId: bigint;
}> {
    return value.map((x)=>from_candid_record_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Zone>): Array<Zone> {
    return value.map((x)=>from_candid_Zone_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaperTradeState>): Array<PaperTradeState> {
    return value.map((x)=>from_candid_PaperTradeState_n4(_uploadFile, _downloadFile, x));
}
function to_candid_TradeSide_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): _TradeSide {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_TradeStyle_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStyle): _TradeStyle {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ZoneType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ZoneType): _ZoneType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ZoneType): {
    support: null;
} | {
    resistance: null;
} {
    return value == ZoneType.support ? {
        support: null
    } : value == ZoneType.resistance ? {
        resistance: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): {
    long: null;
} | {
    short: null;
} {
    return value == TradeSide.long ? {
        long_: null
    } : value == TradeSide.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStyle): {
    scalping: null;
} | {
    dayTrade: null;
} | {
    positionTrade: null;
} | {
    swingTrade: null;
} {
    return value == TradeStyle.scalping ? {
        scalping: null
    } : value == TradeStyle.dayTrade ? {
        dayTrade: null
    } : value == TradeStyle.positionTrade ? {
        positionTrade: null
    } : value == TradeStyle.swingTrade ? {
        swingTrade: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
