/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActiveTrade {
    direction: TradeDirection;
    moduleName: string;
    tradeId: bigint;
    entryPrice: number;
    currentPnl: number;
    symbol: string;
}
export interface ClosedTrade {
    result: TradeResult;
    moduleName: string;
    tradeId: bigint;
    symbol: string;
    finalPnl: number;
}
export enum TradeDirection {
    LONG = "LONG",
    SHORT = "SHORT"
}
export enum TradeResult {
    WIN = "WIN",
    LOSS = "LOSS"
}
export interface backendInterface {
    addActiveTrade(moduleName: string, symbol: string, direction: TradeDirection, entryPrice: number): Promise<bigint>;
    closeTrade(tradeId: bigint, finalPnl: number): Promise<void>;
    getActiveTrades(): Promise<Array<ActiveTrade>>;
    getClosedTrades(): Promise<Array<ClosedTrade>>;
    getClosedTradesByModule(moduleName: string): Promise<Array<ClosedTrade>>;
    getClosedTradesByResult(result: TradeResult): Promise<Array<ClosedTrade>>;
}
import type { ActiveTrade as _ActiveTrade, ClosedTrade as _ClosedTrade, TradeDirection as _TradeDirection, TradeResult as _TradeResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActiveTrade(arg0: string, arg1: string, arg2: TradeDirection, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addActiveTrade(arg0, arg1, to_candid_TradeDirection_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActiveTrade(arg0, arg1, to_candid_TradeDirection_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async closeTrade(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeTrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeTrade(arg0, arg1);
            return result;
        }
    }
    async getActiveTrades(): Promise<Array<ActiveTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTrades();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTrades();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClosedTrades(): Promise<Array<ClosedTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedTrades();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedTrades();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClosedTradesByModule(arg0: string): Promise<Array<ClosedTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedTradesByModule(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedTradesByModule(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClosedTradesByResult(arg0: TradeResult): Promise<Array<ClosedTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedTradesByResult(to_candid_TradeResult_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedTradesByResult(to_candid_TradeResult_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActiveTrade_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveTrade): ActiveTrade {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ClosedTrade_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClosedTrade): ClosedTrade {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TradeResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeResult): TradeResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _TradeResult;
    moduleName: string;
    tradeId: bigint;
    symbol: string;
    finalPnl: number;
}): {
    result: TradeResult;
    moduleName: string;
    tradeId: bigint;
    symbol: string;
    finalPnl: number;
} {
    return {
        result: from_candid_TradeResult_n11(_uploadFile, _downloadFile, value.result),
        moduleName: value.moduleName,
        tradeId: value.tradeId,
        symbol: value.symbol,
        finalPnl: value.finalPnl
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _TradeDirection;
    moduleName: string;
    tradeId: bigint;
    entryPrice: number;
    currentPnl: number;
    symbol: string;
}): {
    direction: TradeDirection;
    moduleName: string;
    tradeId: bigint;
    entryPrice: number;
    currentPnl: number;
    symbol: string;
} {
    return {
        direction: from_candid_TradeDirection_n6(_uploadFile, _downloadFile, value.direction),
        moduleName: value.moduleName,
        tradeId: value.tradeId,
        entryPrice: value.entryPrice,
        currentPnl: value.currentPnl,
        symbol: value.symbol
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WIN: null;
} | {
    LOSS: null;
}): TradeResult {
    return "WIN" in value ? TradeResult.WIN : "LOSS" in value ? TradeResult.LOSS : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LONG: null;
} | {
    SHORT: null;
}): TradeDirection {
    return "LONG" in value ? TradeDirection.LONG : "SHORT" in value ? TradeDirection.SHORT : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActiveTrade>): Array<ActiveTrade> {
    return value.map((x)=>from_candid_ActiveTrade_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClosedTrade>): Array<ClosedTrade> {
    return value.map((x)=>from_candid_ClosedTrade_n9(_uploadFile, _downloadFile, x));
}
function to_candid_TradeDirection_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TradeResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeResult): _TradeResult {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeResult): {
    WIN: null;
} | {
    LOSS: null;
} {
    return value == TradeResult.WIN ? {
        WIN: null
    } : value == TradeResult.LOSS ? {
        LOSS: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    LONG: null;
} | {
    SHORT: null;
} {
    return value == TradeDirection.LONG ? {
        LONG: null
    } : value == TradeDirection.SHORT ? {
        SHORT: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
